// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "delivery-service/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockDelivery_Repository is a mock of Delivery_Repository interface.
type MockDelivery_Repository struct {
	ctrl     *gomock.Controller
	recorder *MockDelivery_RepositoryMockRecorder
}

// MockDelivery_RepositoryMockRecorder is the mock recorder for MockDelivery_Repository.
type MockDelivery_RepositoryMockRecorder struct {
	mock *MockDelivery_Repository
}

// NewMockDelivery_Repository creates a new mock instance.
func NewMockDelivery_Repository(ctrl *gomock.Controller) *MockDelivery_Repository {
	mock := &MockDelivery_Repository{ctrl: ctrl}
	mock.recorder = &MockDelivery_RepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelivery_Repository) EXPECT() *MockDelivery_RepositoryMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockDelivery_Repository) CreateCourier(ctx context.Context, courier *domain.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockDelivery_RepositoryMockRecorder) CreateCourier(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockDelivery_Repository)(nil).CreateCourier), ctx, courier)
}

// GetCourierByID mocks base method.
func (m *MockDelivery_Repository) GetCourierByID(ctx context.Context, courierID string) (*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierByID", ctx, courierID)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierByID indicates an expected call of GetCourierByID.
func (mr *MockDelivery_RepositoryMockRecorder) GetCourierByID(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierByID", reflect.TypeOf((*MockDelivery_Repository)(nil).GetCourierByID), ctx, courierID)
}

// UpdateCourier mocks base method.
func (m *MockDelivery_Repository) UpdateCourier(ctx context.Context, courierID string, update *domain.CourierUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courierID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockDelivery_RepositoryMockRecorder) UpdateCourier(ctx, courierID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockDelivery_Repository)(nil).UpdateCourier), ctx, courierID, update)
}

// ListCouriers mocks base method.
func (m *MockDelivery_Repository) ListCouriers(ctx context.Context, filter *domain.CourierFilter) ([]*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCouriers", ctx, filter)
	ret0, _ := ret[0].([]*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCouriers indicates an expected call of ListCouriers.
func (mr *MockDelivery_RepositoryMockRecorder) ListCouriers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCouriers", reflect.TypeOf((*MockDelivery_Repository)(nil).ListCouriers), ctx, filter)
}

// CreateDeliveryJob mocks base method.
func (m *MockDelivery_Repository) CreateDeliveryJob(ctx context.Context, job *domain.DeliveryJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeliveryJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeliveryJob indicates an expected call of CreateDeliveryJob.
func (mr *MockDelivery_RepositoryMockRecorder) CreateDeliveryJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeliveryJob", reflect.TypeOf((*MockDelivery_Repository)(nil).CreateDeliveryJob), ctx, job)
}

// GetDeliveryJobByID mocks base method.
func (m *MockDelivery_Repository) GetDeliveryJobByID(ctx context.Context, jobID string) (*domain.DeliveryJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryJobByID", ctx, jobID)
	ret0, _ := ret[0].(*domain.DeliveryJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveryJobByID indicates an expected call of GetDeliveryJobByID.
func (mr *MockDelivery_RepositoryMockRecorder) GetDeliveryJobByID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryJobByID", reflect.TypeOf((*MockDelivery_Repository)(nil).GetDeliveryJobByID), ctx, jobID)
}

// GetDeliveryJobByTrackingNumber mocks base method.
func (m *MockDelivery_Repository) GetDeliveryJobByTrackingNumber(ctx context.Context, trackingNumber string) (*domain.DeliveryJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryJobByTrackingNumber", ctx, trackingNumber)
	ret0, _ := ret[0].(*domain.DeliveryJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveryJobByTrackingNumber indicates an expected call of GetDeliveryJobByTrackingNumber.
func (mr *MockDelivery_RepositoryMockRecorder) GetDeliveryJobByTrackingNumber(ctx, trackingNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryJobByTrackingNumber", reflect.TypeOf((*MockDelivery_Repository)(nil).GetDeliveryJobByTrackingNumber), ctx, trackingNumber)
}

// UpdateDeliveryJobStatus mocks base method.
func (m *MockDelivery_Repository) UpdateDeliveryJobStatus(ctx context.Context, jobID string, update *domain.JobStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeliveryJobStatus", ctx, jobID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeliveryJobStatus indicates an expected call of UpdateDeliveryJobStatus.
func (mr *MockDelivery_RepositoryMockRecorder) UpdateDeliveryJobStatus(ctx, jobID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeliveryJobStatus", reflect.TypeOf((*MockDelivery_Repository)(nil).UpdateDeliveryJobStatus), ctx, jobID, update)
}

// GetJobsByCourierID mocks base method.
func (m *MockDelivery_Repository) GetJobsByCourierID(ctx context.Context, courierID string) ([]*domain.DeliveryJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobsByCourierID", ctx, courierID)
	ret0, _ := ret[0].([]*domain.DeliveryJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobsByCourierID indicates an expected call of GetJobsByCourierID.
func (mr *MockDelivery_RepositoryMockRecorder) GetJobsByCourierID(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobsByCourierID", reflect.TypeOf((*MockDelivery_Repository)(nil).GetJobsByCourierID), ctx, courierID)
}
