// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "delivery-service/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRouting_Client is a mock of Routing_Client interface.
type MockRouting_Client struct {
	ctrl     *gomock.Controller
	recorder *MockRouting_ClientMockRecorder
}

// MockRouting_ClientMockRecorder is the mock recorder for MockRouting_Client.
type MockRouting_ClientMockRecorder struct {
	mock *MockRouting_Client
}

// NewMockRouting_Client creates a new mock instance.
func NewMockRouting_Client(ctrl *gomock.Controller) *MockRouting_Client {
	mock := &MockRouting_Client{ctrl: ctrl}
	mock.recorder = &MockRouting_ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouting_Client) EXPECT() *MockRouting_ClientMockRecorder {
	return m.recorder
}

// GetCourierRoute mocks base method.
func (m *MockRouting_Client) GetCourierRoute(ctx context.Context, courierID string) (*domain.DeliveryRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierRoute", ctx, courierID)
	ret0, _ := ret[0].(*domain.DeliveryRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierRoute indicates an expected call of GetCourierRoute.
func (mr *MockRouting_ClientMockRecorder) GetCourierRoute(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierRoute", reflect.TypeOf((*MockRouting_Client)(nil).GetCourierRoute), ctx, courierID)
}
