// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "payment-service/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockKafka_Publisher is a mock of Kafka_Publisher interface.
type MockKafka_Publisher struct {
	ctrl     *gomock.Controller
	recorder *MockKafka_PublisherMockRecorder
}

// MockKafka_PublisherMockRecorder is the mock recorder for MockKafka_Publisher.
type MockKafka_PublisherMockRecorder struct {
	mock *MockKafka_Publisher
}

// NewMockKafka_Publisher creates a new mock instance.
func NewMockKafka_Publisher(ctrl *gomock.Controller) *MockKafka_Publisher {
	mock := &MockKafka_Publisher{ctrl: ctrl}
	mock.recorder = &MockKafka_PublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafka_Publisher) EXPECT() *MockKafka_PublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockKafka_Publisher) Publish(ctx context.Context, topic string, event *domain.PaymentEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockKafka_PublisherMockRecorder) Publish(ctx, topic, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockKafka_Publisher)(nil).Publish), ctx, topic, event)
}
