// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "payment-service/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPayment_Gateway_Client is a mock of Payment_Gateway_Client interface.
type MockPayment_Gateway_Client struct {
	ctrl     *gomock.Controller
	recorder *MockPayment_Gateway_ClientMockRecorder
}

// MockPayment_Gateway_ClientMockRecorder is the mock recorder for MockPayment_Gateway_Client.
type MockPayment_Gateway_ClientMockRecorder struct {
	mock *MockPayment_Gateway_Client
}

// NewMockPayment_Gateway_Client creates a new mock instance.
func NewMockPayment_Gateway_Client(ctrl *gomock.Controller) *MockPayment_Gateway_Client {
	mock := &MockPayment_Gateway_Client{ctrl: ctrl}
	mock.recorder = &MockPayment_Gateway_ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayment_Gateway_Client) EXPECT() *MockPayment_Gateway_ClientMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPayment_Gateway_Client) Charge(ctx context.Context, req *domain.ChargeRequest) (*domain.ChargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, req)
	ret0, _ := ret[0].(*domain.ChargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Charge indicates an expected call of Charge.
func (mr *MockPayment_Gateway_ClientMockRecorder) Charge(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPayment_Gateway_Client)(nil).Charge), ctx, req)
}
