// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "payment-service/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPayment_Repository is a mock of Payment_Repository interface.
type MockPayment_Repository struct {
	ctrl     *gomock.Controller
	recorder *MockPayment_RepositoryMockRecorder
}

// MockPayment_RepositoryMockRecorder is the mock recorder for MockPayment_Repository.
type MockPayment_RepositoryMockRecorder struct {
	mock *MockPayment_Repository
}

// NewMockPayment_Repository creates a new mock instance.
func NewMockPayment_Repository(ctrl *gomock.Controller) *MockPayment_Repository {
	mock := &MockPayment_Repository{ctrl: ctrl}
	mock.recorder = &MockPayment_RepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayment_Repository) EXPECT() *MockPayment_RepositoryMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPayment_Repository) CreatePayment(ctx context.Context, payment *domain.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPayment_RepositoryMockRecorder) CreatePayment(ctx, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPayment_Repository)(nil).CreatePayment), ctx, payment)
}

// GetPaymentByID mocks base method.
func (m *MockPayment_Repository) GetPaymentByID(ctx context.Context, paymentID string) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByID", ctx, paymentID)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByID indicates an expected call of GetPaymentByID.
func (mr *MockPayment_RepositoryMockRecorder) GetPaymentByID(ctx, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByID", reflect.TypeOf((*MockPayment_Repository)(nil).GetPaymentByID), ctx, paymentID)
}

// GetPaymentByOrderID mocks base method.
func (m *MockPayment_Repository) GetPaymentByOrderID(ctx context.Context, orderID string) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByOrderID indicates an expected call of GetPaymentByOrderID.
func (mr *MockPayment_RepositoryMockRecorder) GetPaymentByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByOrderID", reflect.TypeOf((*MockPayment_Repository)(nil).GetPaymentByOrderID), ctx, orderID)
}

// UpdatePaymentStatus mocks base method.
func (m *MockPayment_Repository) UpdatePaymentStatus(ctx context.Context, orderID string, status domain.PaymentStatus, externalRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, orderID, status, externalRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockPayment_RepositoryMockRecorder) UpdatePaymentStatus(ctx, orderID, status, externalRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockPayment_Repository)(nil).UpdatePaymentStatus), ctx, orderID, status, externalRef)
}

// CreateCodCollection mocks base method.
func (m *MockPayment_Repository) CreateCodCollection(ctx context.Context, collection *domain.CodCollection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCodCollection", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCodCollection indicates an expected call of CreateCodCollection.
func (mr *MockPayment_RepositoryMockRecorder) CreateCodCollection(ctx, collection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCodCollection", reflect.TypeOf((*MockPayment_Repository)(nil).CreateCodCollection), ctx, collection)
}

// GetPaymentByExternalRef mocks base method.
func (m *MockPayment_Repository) GetPaymentByExternalRef(ctx context.Context, externalRef string) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByExternalRef", ctx, externalRef)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByExternalRef indicates an expected call of GetPaymentByExternalRef.
func (mr *MockPayment_RepositoryMockRecorder) GetPaymentByExternalRef(ctx, externalRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByExternalRef", reflect.TypeOf((*MockPayment_Repository)(nil).GetPaymentByExternalRef), ctx, externalRef)
}
