// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fujiwara-express/warehouse-service/internal/repository (interfaces: WarehouseRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/fujiwara-express/warehouse-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWarehouseRepository is a mock of WarehouseRepository interface.
type MockWarehouseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWarehouseRepositoryMockRecorder
}

// MockWarehouseRepositoryMockRecorder is the mock recorder for MockWarehouseRepository.
type MockWarehouseRepositoryMockRecorder struct {
	mock *MockWarehouseRepository
}

// NewMockWarehouseRepository creates a new mock instance.
func NewMockWarehouseRepository(ctrl *gomock.Controller) *MockWarehouseRepository {
	mock := &MockWarehouseRepository{ctrl: ctrl}
	mock.recorder = &MockWarehouseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarehouseRepository) EXPECT() *MockWarehouseRepositoryMockRecorder {
	return m.recorder
}

// GetItemByID mocks base method.
func (m *MockWarehouseRepository) GetItemByID(ctx context.Context, id string) (domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", ctx, id)
	ret0, _ := ret[0].(domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockWarehouseRepositoryMockRecorder) GetItemByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockWarehouseRepository)(nil).GetItemByID), ctx, id)
}

// SaveItem mocks base method.
func (m *MockWarehouseRepository) SaveItem(ctx context.Context, item domain.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveItem indicates an expected call of SaveItem.
func (mr *MockWarehouseRepositoryMockRecorder) SaveItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveItem", reflect.TypeOf((*MockWarehouseRepository)(nil).SaveItem), ctx, item)
}
