// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fujiwara-express/warehouse-service/internal/service (interfaces: WarehouseService)

package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/fujiwara-express/warehouse-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWarehouseService is a mock of WarehouseService interface.
type MockWarehouseService struct {
	ctrl     *gomock.Controller
	recorder *MockWarehouseServiceMockRecorder
}

// MockWarehouseServiceMockRecorder is the mock recorder for MockWarehouseService.
type MockWarehouseServiceMockRecorder struct {
	mock *MockWarehouseService
}

// NewMockWarehouseService creates a new mock instance.
func NewMockWarehouseService(ctrl *gomock.Controller) *MockWarehouseService {
	mock := &MockWarehouseService{ctrl: ctrl}
	mock.recorder = &MockWarehouseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarehouseService) EXPECT() *MockWarehouseServiceMockRecorder {
	return m.recorder
}

// CheckStock mocks base method.
func (m *MockWarehouseService) CheckStock(ctx context.Context, id string) (domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStock", ctx, id)
	ret0, _ := ret[0].(domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStock indicates an expected call of CheckStock.
func (mr *MockWarehouseServiceMockRecorder) CheckStock(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStock", reflect.TypeOf((*MockWarehouseService)(nil).CheckStock), ctx, id)
}

// DispatchItem mocks base method.
func (m *MockWarehouseService) DispatchItem(ctx context.Context, id string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchItem", ctx, id, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchItem indicates an expected call of DispatchItem.
func (mr *MockWarehouseServiceMockRecorder) DispatchItem(ctx, id, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchItem", reflect.TypeOf((*MockWarehouseService)(nil).DispatchItem), ctx, id, quantity)
}

// ReceiveItem mocks base method.
func (m *MockWarehouseService) ReceiveItem(ctx context.Context, item domain.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceiveItem indicates an expected call of ReceiveItem.
func (mr *MockWarehouseServiceMockRecorder) ReceiveItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveItem", reflect.TypeOf((*MockWarehouseService)(nil).ReceiveItem), ctx, item)
}
