// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/interface.go -destination internal/repository/mocks/mock_repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/fujiwara-express/pricing-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPricingRepository is a mock of PricingRepository interface.
type MockPricingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPricingRepositoryMockRecorder
	isgomock struct{}
}

// MockPricingRepositoryMockRecorder is the mock recorder for MockPricingRepository.
type MockPricingRepositoryMockRecorder struct {
	mock *MockPricingRepository
}

// NewMockPricingRepository creates a new mock instance.
func NewMockPricingRepository(ctrl *gomock.Controller) *MockPricingRepository {
	mock := &MockPricingRepository{ctrl: ctrl}
	mock.recorder = &MockPricingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingRepository) EXPECT() *MockPricingRepositoryMockRecorder {
	return m.recorder
}

// GetRate mocks base method.
func (m *MockPricingRepository) GetRate(ctx context.Context, zoneID, serviceType string) (domain.Rate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", ctx, zoneID, serviceType)
	ret0, _ := ret[0].(domain.Rate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRate indicates an expected call of GetRate.
func (mr *MockPricingRepositoryMockRecorder) GetRate(ctx, zoneID, serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockPricingRepository)(nil).GetRate), ctx, zoneID, serviceType)
}

// GetSurcharge mocks base method.
func (m *MockPricingRepository) GetSurcharge(ctx context.Context, surchargeType string) (domain.Surcharge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurcharge", ctx, surchargeType)
	ret0, _ := ret[0].(domain.Surcharge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurcharge indicates an expected call of GetSurcharge.
func (mr *MockPricingRepositoryMockRecorder) GetSurcharge(ctx, surchargeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurcharge", reflect.TypeOf((*MockPricingRepository)(nil).GetSurcharge), ctx, surchargeType)
}

// GetZone mocks base method.
func (m *MockPricingRepository) GetZone(ctx context.Context, originCode, destCode string) (domain.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZone", ctx, originCode, destCode)
	ret0, _ := ret[0].(domain.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZone indicates an expected call of GetZone.
func (mr *MockPricingRepositoryMockRecorder) GetZone(ctx, originCode, destCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZone", reflect.TypeOf((*MockPricingRepository)(nil).GetZone), ctx, originCode, destCode)
}
