apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: routing
  labels:
    app: routing-service
spec:
  type: ClusterIP
  selector:
    app: routing-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
