// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/report-and-analytics/internal/domain"
	"go.uber.org/mock/gomock"
)

// MockReportService is a mock of ReportService interface.
type MockReportService struct {
	ctrl     *gomock.Controller
	recorder *MockReportServiceMockRecorder
}

// MockReportServiceMockRecorder is the mock recorder for MockReportService.
type MockReportServiceMockRecorder struct {
	mock *MockReportService
}

// NewMockReportService creates a new mock instance.
func NewMockReportService(ctrl *gomock.Controller) *MockReportService {
	mock := &MockReportService{ctrl: ctrl}
	mock.recorder = &MockReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportService) EXPECT() *MockReportServiceMockRecorder {
	return m.recorder
}

// GetOrderReport mocks base method.
func (m *MockReportService) GetOrderReport(ctx context.Context, f domain.OrderReportFilter) (*domain.OrderReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderReport", ctx, f)
	ret0, _ := ret[0].(*domain.OrderReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderReport indicates an expected call of GetOrderReport.
func (mr *MockReportServiceMockRecorder) GetOrderReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderReport", reflect.TypeOf((*MockReportService)(nil).GetOrderReport), ctx, f)
}

// GetDeliveryPerformanceReport mocks base method.
func (m *MockReportService) GetDeliveryPerformanceReport(ctx context.Context, f domain.DeliveryPerformanceFilter) (*domain.DeliveryPerformanceReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryPerformanceReport", ctx, f)
	ret0, _ := ret[0].(*domain.DeliveryPerformanceReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveryPerformanceReport indicates an expected call of GetDeliveryPerformanceReport.
func (mr *MockReportServiceMockRecorder) GetDeliveryPerformanceReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryPerformanceReport", reflect.TypeOf((*MockReportService)(nil).GetDeliveryPerformanceReport), ctx, f)
}

// GetRevenueReport mocks base method.
func (m *MockReportService) GetRevenueReport(ctx context.Context, f domain.RevenueFilter) (*domain.RevenueReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevenueReport", ctx, f)
	ret0, _ := ret[0].(*domain.RevenueReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevenueReport indicates an expected call of GetRevenueReport.
func (mr *MockReportServiceMockRecorder) GetRevenueReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevenueReport", reflect.TypeOf((*MockReportService)(nil).GetRevenueReport), ctx, f)
}

// GetHubPerformanceReport mocks base method.
func (m *MockReportService) GetHubPerformanceReport(ctx context.Context, f domain.HubPerformanceFilter) (*domain.HubPerformanceReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHubPerformanceReport", ctx, f)
	ret0, _ := ret[0].(*domain.HubPerformanceReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHubPerformanceReport indicates an expected call of GetHubPerformanceReport.
func (mr *MockReportServiceMockRecorder) GetHubPerformanceReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHubPerformanceReport", reflect.TypeOf((*MockReportService)(nil).GetHubPerformanceReport), ctx, f)
}
