// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/report-and-analytics/internal/domain"
	"go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// GetOrderReport mocks base method.
func (m *MockReportRepository) GetOrderReport(ctx context.Context, f domain.OrderReportFilter) (*domain.OrderReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderReport", ctx, f)
	ret0, _ := ret[0].(*domain.OrderReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderReport indicates an expected call of GetOrderReport.
func (mr *MockReportRepositoryMockRecorder) GetOrderReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderReport", reflect.TypeOf((*MockReportRepository)(nil).GetOrderReport), ctx, f)
}

// GetDeliveryPerformanceReport mocks base method.
func (m *MockReportRepository) GetDeliveryPerformanceReport(ctx context.Context, f domain.DeliveryPerformanceFilter) (*domain.DeliveryPerformanceReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryPerformanceReport", ctx, f)
	ret0, _ := ret[0].(*domain.DeliveryPerformanceReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveryPerformanceReport indicates an expected call of GetDeliveryPerformanceReport.
func (mr *MockReportRepositoryMockRecorder) GetDeliveryPerformanceReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryPerformanceReport", reflect.TypeOf((*MockReportRepository)(nil).GetDeliveryPerformanceReport), ctx, f)
}

// GetRevenueReport mocks base method.
func (m *MockReportRepository) GetRevenueReport(ctx context.Context, f domain.RevenueFilter) (*domain.RevenueReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevenueReport", ctx, f)
	ret0, _ := ret[0].(*domain.RevenueReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevenueReport indicates an expected call of GetRevenueReport.
func (mr *MockReportRepositoryMockRecorder) GetRevenueReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevenueReport", reflect.TypeOf((*MockReportRepository)(nil).GetRevenueReport), ctx, f)
}

// GetHubPerformanceReport mocks base method.
func (m *MockReportRepository) GetHubPerformanceReport(ctx context.Context, f domain.HubPerformanceFilter) (*domain.HubPerformanceReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHubPerformanceReport", ctx, f)
	ret0, _ := ret[0].(*domain.HubPerformanceReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHubPerformanceReport indicates an expected call of GetHubPerformanceReport.
func (mr *MockReportRepositoryMockRecorder) GetHubPerformanceReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHubPerformanceReport", reflect.TypeOf((*MockReportRepository)(nil).GetHubPerformanceReport), ctx, f)
}
