// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"
	"time"

	"go.uber.org/mock/gomock"
)

// MockTrackingClient is a mock of TrackingClient interface.
type MockTrackingClient struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingClientMockRecorder
}

// MockTrackingClientMockRecorder is the mock recorder for MockTrackingClient.
type MockTrackingClientMockRecorder struct {
	mock *MockTrackingClient
}

// NewMockTrackingClient creates a new mock instance.
func NewMockTrackingClient(ctrl *gomock.Controller) *MockTrackingClient {
	mock := &MockTrackingClient{ctrl: ctrl}
	mock.recorder = &MockTrackingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingClient) EXPECT() *MockTrackingClientMockRecorder {
	return m.recorder
}

// PublishPickedUpEvent mocks base method.
func (m *MockTrackingClient) PublishPickedUpEvent(ctx context.Context, pickupID, orderID string, ts time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPickedUpEvent", ctx, pickupID, orderID, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPickedUpEvent indicates an expected call of PublishPickedUpEvent.
func (mr *MockTrackingClientMockRecorder) PublishPickedUpEvent(ctx, pickupID, orderID, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPickedUpEvent", reflect.TypeOf((*MockTrackingClient)(nil).PublishPickedUpEvent), ctx, pickupID, orderID, ts)
}
