// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/pickup-service/internal/domain"
	"github.com/pickup-service/internal/repository"
	"go.uber.org/mock/gomock"
)

// MockPickupRepository is a mock of PickupRepository interface.
type MockPickupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPickupRepositoryMockRecorder
}

// MockPickupRepositoryMockRecorder is the mock recorder for MockPickupRepository.
type MockPickupRepositoryMockRecorder struct {
	mock *MockPickupRepository
}

// NewMockPickupRepository creates a new mock instance.
func NewMockPickupRepository(ctrl *gomock.Controller) *MockPickupRepository {
	mock := &MockPickupRepository{ctrl: ctrl}
	mock.recorder = &MockPickupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPickupRepository) EXPECT() *MockPickupRepositoryMockRecorder {
	return m.recorder
}

// CreatePickup mocks base method.
func (m *MockPickupRepository) CreatePickup(ctx context.Context, p *domain.Pickup) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePickup", ctx, p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePickup indicates an expected call of CreatePickup.
func (mr *MockPickupRepositoryMockRecorder) CreatePickup(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePickup", reflect.TypeOf((*MockPickupRepository)(nil).CreatePickup), ctx, p)
}

// GetPickupByID mocks base method.
func (m *MockPickupRepository) GetPickupByID(ctx context.Context, id string) (*domain.Pickup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPickupByID", ctx, id)
	ret0, _ := ret[0].(*domain.Pickup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPickupByID indicates an expected call of GetPickupByID.
func (mr *MockPickupRepositoryMockRecorder) GetPickupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPickupByID", reflect.TypeOf((*MockPickupRepository)(nil).GetPickupByID), ctx, id)
}

// UpdatePickup mocks base method.
func (m *MockPickupRepository) UpdatePickup(ctx context.Context, p *domain.Pickup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePickup", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePickup indicates an expected call of UpdatePickup.
func (mr *MockPickupRepositoryMockRecorder) UpdatePickup(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePickup", reflect.TypeOf((*MockPickupRepository)(nil).UpdatePickup), ctx, p)
}

// ListPickups mocks base method.
func (m *MockPickupRepository) ListPickups(ctx context.Context, filters repository.ListFilters) ([]*domain.Pickup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPickups", ctx, filters)
	ret0, _ := ret[0].([]*domain.Pickup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPickups indicates an expected call of ListPickups.
func (mr *MockPickupRepositoryMockRecorder) ListPickups(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPickups", reflect.TypeOf((*MockPickupRepository)(nil).ListPickups), ctx, filters)
}

// CreatePickupAttempt mocks base method.
func (m *MockPickupRepository) CreatePickupAttempt(ctx context.Context, a *domain.PickupAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePickupAttempt", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePickupAttempt indicates an expected call of CreatePickupAttempt.
func (mr *MockPickupRepositoryMockRecorder) CreatePickupAttempt(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePickupAttempt", reflect.TypeOf((*MockPickupRepository)(nil).CreatePickupAttempt), ctx, a)
}
