// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/pickup-service/internal/domain"
	"github.com/pickup-service/internal/service"
	"go.uber.org/mock/gomock"
)

// MockPickupService is a mock of PickupService interface.
type MockPickupService struct {
	ctrl     *gomock.Controller
	recorder *MockPickupServiceMockRecorder
}

// MockPickupServiceMockRecorder is the mock recorder for MockPickupService.
type MockPickupServiceMockRecorder struct {
	mock *MockPickupService
}

// NewMockPickupService creates a new mock instance.
func NewMockPickupService(ctrl *gomock.Controller) *MockPickupService {
	mock := &MockPickupService{ctrl: ctrl}
	mock.recorder = &MockPickupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPickupService) EXPECT() *MockPickupServiceMockRecorder {
	return m.recorder
}

// RequestPickup mocks base method.
func (m *MockPickupService) RequestPickup(ctx context.Context, req service.RequestPickupInput) (*service.RequestPickupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPickup", ctx, req)
	ret0, _ := ret[0].(*service.RequestPickupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestPickup indicates an expected call of RequestPickup.
func (mr *MockPickupServiceMockRecorder) RequestPickup(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPickup", reflect.TypeOf((*MockPickupService)(nil).RequestPickup), ctx, req)
}

// AssignCourier mocks base method.
func (m *MockPickupService) AssignCourier(ctx context.Context, pickupID, courierID string) (*service.AssignCourierOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, pickupID, courierID)
	ret0, _ := ret[0].(*service.AssignCourierOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockPickupServiceMockRecorder) AssignCourier(ctx, pickupID, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockPickupService)(nil).AssignCourier), ctx, pickupID, courierID)
}

// UpdatePickupStatus mocks base method.
func (m *MockPickupService) UpdatePickupStatus(ctx context.Context, pickupID string, status domain.Status) (*service.UpdateStatusOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePickupStatus", ctx, pickupID, status)
	ret0, _ := ret[0].(*service.UpdateStatusOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePickupStatus indicates an expected call of UpdatePickupStatus.
func (mr *MockPickupServiceMockRecorder) UpdatePickupStatus(ctx, pickupID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePickupStatus", reflect.TypeOf((*MockPickupService)(nil).UpdatePickupStatus), ctx, pickupID, status)
}

// GetPickup mocks base method.
func (m *MockPickupService) GetPickup(ctx context.Context, pickupID string) (*domain.Pickup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPickup", ctx, pickupID)
	ret0, _ := ret[0].(*domain.Pickup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPickup indicates an expected call of GetPickup.
func (mr *MockPickupServiceMockRecorder) GetPickup(ctx, pickupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPickup", reflect.TypeOf((*MockPickupService)(nil).GetPickup), ctx, pickupID)
}

// ListPickups mocks base method.
func (m *MockPickupService) ListPickups(ctx context.Context, filters service.ListFilters) ([]*domain.Pickup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPickups", ctx, filters)
	ret0, _ := ret[0].([]*domain.Pickup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPickups indicates an expected call of ListPickups.
func (mr *MockPickupServiceMockRecorder) ListPickups(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPickups", reflect.TypeOf((*MockPickupService)(nil).ListPickups), ctx, filters)
}

// CancelPickup mocks base method.
func (m *MockPickupService) CancelPickup(ctx context.Context, pickupID string) (*service.CancelPickupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPickup", ctx, pickupID)
	ret0, _ := ret[0].(*service.CancelPickupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPickup indicates an expected call of CancelPickup.
func (mr *MockPickupServiceMockRecorder) CancelPickup(ctx, pickupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPickup", reflect.TypeOf((*MockPickupService)(nil).CancelPickup), ctx, pickupID)
}
