// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/pickup-service/internal/client"
	"go.uber.org/mock/gomock"
)

// MockDeliveryClient is a mock of DeliveryClient interface.
type MockDeliveryClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryClientMockRecorder
}

// MockDeliveryClientMockRecorder is the mock recorder for MockDeliveryClient.
type MockDeliveryClientMockRecorder struct {
	mock *MockDeliveryClient
}

// NewMockDeliveryClient creates a new mock instance.
func NewMockDeliveryClient(ctrl *gomock.Controller) *MockDeliveryClient {
	mock := &MockDeliveryClient{ctrl: ctrl}
	mock.recorder = &MockDeliveryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryClient) EXPECT() *MockDeliveryClientMockRecorder {
	return m.recorder
}

// GetAvailableCouriers mocks base method.
func (m *MockDeliveryClient) GetAvailableCouriers(ctx context.Context, cityCode string) ([]client.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableCouriers", ctx, cityCode)
	ret0, _ := ret[0].([]client.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableCouriers indicates an expected call of GetAvailableCouriers.
func (mr *MockDeliveryClientMockRecorder) GetAvailableCouriers(ctx, cityCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableCouriers", reflect.TypeOf((*MockDeliveryClient)(nil).GetAvailableCouriers), ctx, cityCode)
}
