// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockNotificationClient is a mock of NotificationClient interface.
type MockNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientMockRecorder
}

// MockNotificationClientMockRecorder is the mock recorder for MockNotificationClient.
type MockNotificationClientMockRecorder struct {
	mock *MockNotificationClient
}

// NewMockNotificationClient creates a new mock instance.
func NewMockNotificationClient(ctrl *gomock.Controller) *MockNotificationClient {
	mock := &MockNotificationClient{ctrl: ctrl}
	mock.recorder = &MockNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationClient) EXPECT() *MockNotificationClientMockRecorder {
	return m.recorder
}

// NotifyCourierEnRoute mocks base method.
func (m *MockNotificationClient) NotifyCourierEnRoute(ctx context.Context, contactName, contactPhone, courierID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyCourierEnRoute", ctx, contactName, contactPhone, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyCourierEnRoute indicates an expected call of NotifyCourierEnRoute.
func (mr *MockNotificationClientMockRecorder) NotifyCourierEnRoute(ctx, contactName, contactPhone, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCourierEnRoute", reflect.TypeOf((*MockNotificationClient)(nil).NotifyCourierEnRoute), ctx, contactName, contactPhone, courierID)
}
