// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"
	"time"

	"github.com/notification-service/internal/domain"
	"go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// CreateNotificationLog mocks base method.
func (m *MockNotificationRepository) CreateNotificationLog(ctx context.Context, log *domain.NotificationLog) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationLog", ctx, log)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotificationLog indicates an expected call of CreateNotificationLog.
func (mr *MockNotificationRepositoryMockRecorder) CreateNotificationLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationLog", reflect.TypeOf((*MockNotificationRepository)(nil).CreateNotificationLog), ctx, log)
}

// GetNotificationLogByID mocks base method.
func (m *MockNotificationRepository) GetNotificationLogByID(ctx context.Context, id string) (*domain.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationLogByID", ctx, id)
	ret0, _ := ret[0].(*domain.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationLogByID indicates an expected call of GetNotificationLogByID.
func (mr *MockNotificationRepositoryMockRecorder) GetNotificationLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationLogByID", reflect.TypeOf((*MockNotificationRepository)(nil).GetNotificationLogByID), ctx, id)
}

// UpdateNotificationLogStatus mocks base method.
func (m *MockNotificationRepository) UpdateNotificationLogStatus(ctx context.Context, id string, status domain.NotifStatus, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationLogStatus", ctx, id, status, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationLogStatus indicates an expected call of UpdateNotificationLogStatus.
func (mr *MockNotificationRepositoryMockRecorder) UpdateNotificationLogStatus(ctx, id, status, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationLogStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateNotificationLogStatus), ctx, id, status, sentAt)
}

// ListTemplates mocks base method.
func (m *MockNotificationRepository) ListTemplates(ctx context.Context) ([]*domain.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx)
	ret0, _ := ret[0].([]*domain.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockNotificationRepositoryMockRecorder) ListTemplates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockNotificationRepository)(nil).ListTemplates), ctx)
}

// GetTemplateByID mocks base method.
func (m *MockNotificationRepository) GetTemplateByID(ctx context.Context, id string) (*domain.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByID", ctx, id)
	ret0, _ := ret[0].(*domain.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByID indicates an expected call of GetTemplateByID.
func (mr *MockNotificationRepositoryMockRecorder) GetTemplateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByID", reflect.TypeOf((*MockNotificationRepository)(nil).GetTemplateByID), ctx, id)
}

// CreateTemplate mocks base method.
func (m *MockNotificationRepository) CreateTemplate(ctx context.Context, t *domain.NotificationTemplate) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, t)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockNotificationRepositoryMockRecorder) CreateTemplate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockNotificationRepository)(nil).CreateTemplate), ctx, t)
}

// UpdateTemplate mocks base method.
func (m *MockNotificationRepository) UpdateTemplate(ctx context.Context, id, subject, bodyTemplate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, id, subject, bodyTemplate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockNotificationRepositoryMockRecorder) UpdateTemplate(ctx, id, subject, bodyTemplate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateTemplate), ctx, id, subject, bodyTemplate)
}
