// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockSendGridClient is a mock of SendGridClient interface.
type MockSendGridClient struct {
	ctrl     *gomock.Controller
	recorder *MockSendGridClientMockRecorder
}

// MockSendGridClientMockRecorder is the mock recorder for MockSendGridClient.
type MockSendGridClientMockRecorder struct {
	mock *MockSendGridClient
}

// NewMockSendGridClient creates a new mock instance.
func NewMockSendGridClient(ctrl *gomock.Controller) *MockSendGridClient {
	mock := &MockSendGridClient{ctrl: ctrl}
	mock.recorder = &MockSendGridClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendGridClient) EXPECT() *MockSendGridClientMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockSendGridClient) SendEmail(ctx context.Context, recipient, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, recipient, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockSendGridClientMockRecorder) SendEmail(ctx, recipient, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockSendGridClient)(nil).SendEmail), ctx, recipient, subject, body)
}
