// Code generated by mockery; DO NOT EDIT.
// Manually created mock using go.uber.org/mock/gomock

package mocks

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockWhatsAppClient is a mock of WhatsAppClient interface.
type MockWhatsAppClient struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppClientMockRecorder
}

// MockWhatsAppClientMockRecorder is the mock recorder for MockWhatsAppClient.
type MockWhatsAppClientMockRecorder struct {
	mock *MockWhatsAppClient
}

// NewMockWhatsAppClient creates a new mock instance.
func NewMockWhatsAppClient(ctrl *gomock.Controller) *MockWhatsAppClient {
	mock := &MockWhatsAppClient{ctrl: ctrl}
	mock.recorder = &MockWhatsAppClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsAppClient) EXPECT() *MockWhatsAppClientMockRecorder {
	return m.recorder
}

// SendWhatsApp mocks base method.
func (m *MockWhatsAppClient) SendWhatsApp(ctx context.Context, phone, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWhatsApp", ctx, phone, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWhatsApp indicates an expected call of SendWhatsApp.
func (mr *MockWhatsAppClientMockRecorder) SendWhatsApp(ctx, phone, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWhatsApp", reflect.TypeOf((*MockWhatsAppClient)(nil).SendWhatsApp), ctx, phone, message)
}
